version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.43
    container_name: jaeger
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: :9411
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    restart: unless-stopped

  app:
    build: ./app
    container_name: my-app
    ports:
      - 8080:8080
    environment:
      - JAEGER_AGENT_HOST=jaeger
    depends_on:
      - jaeger
